### ISSUE TITLE
Error when running "python3 Brute_Force.py -T Account_Twitter -l File_list"

### ISSUE THREAD

**Issue by COD1EINE** [lunnar211/HACKER_DK#2]
![image](https://user-images.githubusercontent.com/89225155/131316175-3abe2c29-750a-4c9a-92b3-7315ecb9c01d.png)

**Comment by supunsathsara** [comment]
@COD1EINE 
It's because 
- Account_Twitter means the twitter username that you trying to Brute Force.
- File_list means the list of passwords that you're using for the attack.
So you have to replace those words with the details of the victim.

**Comment by COD1EINE** [comment]
ok thanks
